#!/bin/bash

set -e

# Version 2013-04-02
#   Changed CLFS to BUILDDIR
#   Addressed case where SBU can't be calculated
#   Renamed .../sources/clfs to .../sources/logs
#   Update makeShellScript to use external sed script
#   Changed the completion flag from a file to an entry in the log
#   Added path for OOM and sedScript to build.config
#   Conditional editing for fpu=none case done with build.config file

# Version 2013-03-26
#   Update redirect for patch download from > to >>
#   Moved BOOK_ARCH to build.config
#   Updated initDU to address case when ${CLFS} not yet created.
#   Added makeReport
#   Removed final shellScript
#   Update BOOK_ARCH to PLATFORM and gitBOOK to BOOK to be consistent with JHALFS

# Version   2013-03-25
#   Outputs are saved to log files in ${CLFS}/sources/clfs
#   Key stats are save to log file - start/stop times, disk usage at key points
#   OOM moved to arch specific folder
#   Patch download integrated into package download
#   Progress indicator reformatted
#   Some commands "silenced", e.g. cd -.

aFormat="%-5s %-12s %-37s %-6s %-38s %-10s %-8s \n"

source $PWD/build.config



doPrep () {





[ -d gitBOOK/$BOOK ] || git clone $REPO gitBOOK/$BOOK

cd gitBOOK/$BOOK
git pull
cd - > /dev/null

[ -d gitBOOK/$BOOK/render/html/${PLATFORM} ] || renderBook


[ -d /home/clfs ] && ( [ -f ${BUILDDIR}/sources/logs/final-preps/settingenvironment.log ]  || rm -f /home/clfs/.bashrc )

}

renderBook () {

echo "im rendering"

cd gitBOOK/$BOOK/BOOK

make

cd -  > /dev/null

}


doDownload () {

        
      pkg=${pkgUrl##*/}

      echo "Preparing "$base

      [ -f $SRC_ARCHIVE/$pkg ] || wget -P $SRC_ARCHIVE  $pkgUrl

 

      tarType=${pkgUrl##*.}

      pkgFolder=${pkg%%.tar*}

      buildFolder=$( echo -n $pkgFolder | cut -d- -f1 )"-build"

      case $tarType in

            bz2) tar -xjf $SRC_ARCHIVE/$pkg -C ${BUILDDIR}/sources/  ;;

            tar) tar -xvf $SRC_ARCHIVE/$pkg -C ${BUILDDIR}/sources/  ;;

            gz)   tar -xzf $SRC_ARCHIVE/$pkg -C ${BUILDDIR}/sources/  ;;
            
            xz) tar -Jxf $SRC_ARCHIVE/$pkg -C ${BUILDDIR}/sources/  ;;

            *)    echo "Unrecognized archive format " && exit 1   ;;

      esac
   
   
  
   chown -R clfs $( echo -n $base | sed s#'${BUILDDIR}'#${BUILDDIR}#g )
   [ -z $patchUrl ] || wget -P ${BUILDDIR}/sources $patchUrl > /dev/null 2>>log
   [ -z $patchUrl ] || chown -R clfs  ${BUILDDIR}/sources/*.patch 

}


makeScript () {

echo "#!/bin/sh" > shellScript
echo "source $PWD/build.config" >> shellScript
echo '[ -f ~/.bashrc ] && source ~/.bashrc' >> shellScript
echo "pushd $PWD" >> shellScript
echo "cd $base " >> shellScript

cat $scriptDir/$rootPage | hxselect kbd -c -s '\n' | sed -f $SED >> shellScript  # scrape commands from page
echo 'echo "exitCode="$?' >> shellScript
echo "popd " >> shellScript
# The following helps to clean up some html oddities

chmod 777 shellScript

}

doCleanUp () {

    rm -r $( echo -n $base | sed s#'${BUILDDIR}'#${BUILDDIR}#g )

    for aPatch in `ls ${BUILDDIR}/sources/ | grep -e "patch" `
    do
        rm ${BUILDDIR}/sources/$aPatch
    done

    for aBuildDir in `ls ${BUILDDIR}/sources/ | grep -e "-build" `
    do
        rm -r  ${BUILDDIR}/sources/$aBuildDir
    done        
    
}

makeReport () {

[ -e shellScript ] && rm shellScript
if [ -f ${BUILDDIR}/sources/logs/cross-tools/binutils.log ]
then
SBU=$(( $( grep -e "finalTime" ${BUILDDIR}/sources/logs/cross-tools/binutils.log | cut -d= -f2 ) - \
        $( grep -e "initTime" ${BUILDDIR}/sources/logs/cross-tools/binutils.log | cut -d= -f2 ) ))
else
    SBU=1
fi    

echo "The contents of the build.config file was:"
cat build.config

printf "%30s %5s %5s %5s %5s %5s  \n" "Page"  "Initial DU (kb)" "Build DU (kb)" "Final DU (kb)" "elapsedTime (s)"  "elaspsed Time (SBU)"

aFormat="%-35s  %9d %9d %9d %9d %3d \n"

for  pageEntry in $( cat localBOOK/$BOOK/${PLATFORM}/OOM )
do
    
    
    rootPage=$( echo -n $pageEntry | cut -d'#' -f1 )

    
    log=$( echo -n $rootPage | sed s#html#log#g )   
    
    initDU=$( grep -e "initDU" ${BUILDDIR}/sources/logs/$log | cut -d= -f2 )
    
    initTime=$( grep -e "initTime" ${BUILDDIR}/sources/logs/$log | cut -d= -f2 )
    
    maxDU=$( grep -e "maxDU" ${BUILDDIR}/sources/logs/$log | cut -d= -f2 )
    
      
    buildDU=$(( maxDU - initDU))
    
    finalDU=$( grep -e "finalDU" ${BUILDDIR}/sources/logs/$log | cut -d= -f2 )
    
    finalTime=$( grep -e "finalTime" ${BUILDDIR}/sources/logs/$log | cut -d= -f2 )
    
    elapsedTime=$(( $finalTime - $initTime ))
    
    buildSBU=$(( $elapsedTime / $SBU ))
    
    printf "$aFormat"  $rootPage $initDU $buildDU $finalDU $elapsedTime $buildSBU 
      
done 

mv summary ${BUILDDIR}/sources/logs



}

doPrep

#OOM=Order of March. This file contains page url, which user executes, what directory to start from, and 
# the url for the source package to download
#Variations of while read pageEntry do not work. uClibc requires manual entry. These entries finish
# reading the file 


for  pageEntry in $( cat $OOM )
do
    
    
    rootPage=$( echo -n $pageEntry | cut -d'#' -f1 )

    user=$( echo -n $pageEntry | cut -d'#' -f2 )

    base=$( echo -n $pageEntry | cut -d'#' -f3 )
    
    pkgUrl=$( echo -n $pageEntry | cut -d'#' -f4 )
    
    patchUrl=$( echo -n $pageEntry | cut -d'#' -f5 )
    
    log=$( echo -n $rootPage | sed s#html#log#g )   
    
    returnCode=$( grep -e "exitCode" ${BUILDDIR}/sources/logs/$log 2>/dev/null | cut -d= -f2)
    [ "$returnCode" = "0"  ] && continue
    
    initDU=$( du -ks ${BUILDDIR} 2>/dev/null | cut -f1 ) 
    
    [ "$initDU" = "" ] && initDU=0
    
    echo "initDU="$initDU > log
    
    [ -z $pkgUrl ] || doDownload
    
    echo "initTime="`date +%s` >> log
    
   #Select which directory to pull page from.
   scriptDir=gitBOOK/$BOOK/render/html/${PLATFORM}/
   myBOOK=git         
   [  -e localBOOK/$BOOK/${PLATFORM}/$rootPage ] && scriptDir=localBOOK/$BOOK/${PLATFORM}/
   [  -e localBOOK/$BOOK/${PLATFORM}/$rootPage ] && myBOOK=local                  
   makeScript
   
  
   printf "$aFormat" $user "is executing" $rootPage "from" $base "using" $myBOOK 
   su -c $PWD/shellScript -s /bin/bash ${user} >> log 2>&1
        
   
    
    maxDU=$( du -ks ${BUILDDIR} | cut -f1 )  
    echo "maxDU="$maxDU >> log
    echo "finalTime="`date +%s` >> log
    
    [ -z $pkgUrl ] || doCleanUp
    
    
    finalDU=$( du -ks ${BUILDDIR} | cut -f1 )  
    echo "finalDU="$finalDU >> log
    mv log  ${BUILDDIR}/sources/logs/$log
    
   
    returnCode=$( grep -e "exitCode" ${BUILDDIR}/sources/logs/$log | cut -d= -f2)
    [ $returnCode -eq 0 ] || break
      
done 
returnCode=$( grep -e "exitCode" ${BUILDDIR}/sources/logs/$log 2>>/dev/null  | cut -d= -f2)
( [ $returnCode -eq 0 ] && echo "Congratulations system build complete " ) || echo "Abnormal Termination"

[ $returnCode -eq 0 ] && makeReport > summary
