#!/bin/sh
source /home/home/kanj/gitHUB/aCLFS/build.config
[ -f ~/.bashrc ] && source ~/.bashrc
pushd /home/home/kanj/gitHUB/aCLFS
cd /opt/sys.i386/sources/gcc-4.4.1 
patch -Np1 -i ../gcc-4.4.1-branch_update-1.patch
mkdir -v ../gcc-build
cd ../gcc-build
AR=ar LDFLAGS="-Wl,-rpath,${CLFS}/cross-tools/lib" \
    ../gcc-4.4.1/configure --prefix=${CLFS}/cross-tools \
    --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
    --disable-multilib --with-sysroot=${CLFS} --disable-nls \
    --without-headers --with-newlib --disable-decimal-float \
    --disable-libgomp --disable-libmudflap --disable-libssp \
    --with-mpfr=${CLFS}/cross-tools --with-gmp=${CLFS}/cross-tools \
    --with-ppl=${CLFS}/cross-tools --with-cloog=${CLFS}/cross-tools \
    --disable-shared --disable-threads --enable-languages=c
make all-gcc all-target-libgcc
make install-gcc install-target-libgcc
 [ $? = 0 ] && touch ${CLFS}/sources/clfs/cross-tools/gcc-static.html
popd 
