#!/bin/sh
source /home/home/kanj/gitHUB/aCLFS/build.config
[ -f ~/.bashrc ] && source ~/.bashrc
pushd /home/home/kanj/gitHUB/aCLFS
cd $PWD 
echo CLFS-Embedded-GIT-0.0.1-20120922 > ${CLFS}/etc/clfs-release
 [ $? = 0 ] && touch ${CLFS}/sources/clfs/the-end/theend.html
popd 
